name: 'Install dependencies'
description: 'Setup Node, pnpm and install dependencies'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v3
      name: Install pnpm
      with:
        version: 8
        run_install: false

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --ignore-scripts
